language: node_js
node_js:
  - 16

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy:v9 elochukwu/reverseproxy:v9
  - docker tag udagram-frontend:v9 elochukwu/udagram-frontend:v9
  - docker tag udagram-api-user:v9 elochukwu/udagram-api-user:v9
  - docker tag udagram-api-feed:v9 elochukwu/udagram-api-feed:v9

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push elochukwu/reverseproxy:v9
  - docker push elochukwu/udagram-frontend:v9
  - docker push elochukwu/udagram-api-user:v9
  - docker push elochukwu/udagram-api-feed:v9